/* Generated by scripts/build.js. Source: src/content/*.js */

/* ===== src/common/settings.js ===== */
/* Linux.do 工具箱 — 设置模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  const DEFAULT_SETTINGS = Object.freeze({
    enablePostActions: true,
    enableBase64Decode: true,
    enableSplitLayout: false,
    includeMetadata: true,
    replaceUploadUrls: true,
  });

  function hasChromeStorage() {
    return typeof chrome !== 'undefined' && Boolean(chrome.storage?.sync);
  }

  function normalizeSettings(value = {}) {
    return { ...DEFAULT_SETTINGS, ...value };
  }

  function getSettings() {
    if (!hasChromeStorage()) {
      return Promise.resolve(normalizeSettings());
    }

    return new Promise((resolve) => {
      chrome.storage.sync.get(DEFAULT_SETTINGS, (items) => {
        if (chrome.runtime?.lastError) {
          resolve(normalizeSettings());
          return;
        }
        resolve(normalizeSettings(items));
      });
    });
  }

  function saveSettings(partialSettings) {
    if (!hasChromeStorage()) {
      return Promise.resolve(normalizeSettings(partialSettings));
    }

    return new Promise((resolve, reject) => {
      chrome.storage.sync.set(partialSettings, () => {
        if (chrome.runtime?.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
          return;
        }
        resolve();
      });
    });
  }

  function onSettingsChanged(callback) {
    if (!hasChromeStorage() || !chrome.storage?.onChanged) return;

    chrome.storage.onChanged.addListener((changes, areaName) => {
      if (areaName !== 'sync') return;
      const changedKeys = Object.keys(changes);
      const settingsKeys = Object.keys(DEFAULT_SETTINGS);
      if (!changedKeys.some((key) => settingsKeys.includes(key))) return;
      getSettings().then(callback).catch(() => callback(normalizeSettings()));
    });
  }

  namespace.settings = {
    DEFAULT_SETTINGS,
    getSettings,
    saveSettings,
    onSettingsChanged,
  };
})();


/* ===== src/content/markdown.js ===== */
/* Linux.do 工具箱 — Markdown 转换模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  // 检测内容是否为 HTML（而非纯 Markdown）。
  function isHtmlContent(text) {
    const trimmed = text.trim();
    if (!trimmed) return false;

    const parser = new DOMParser();
    const doc = parser.parseFromString(trimmed, 'text/html');
    const elCount = doc.body.querySelectorAll('*').length;

    if (elCount > 2) return true;

    for (const el of doc.body.querySelectorAll('*')) {
      if (el.attributes.length > 0) return true;
    }

    return /^<(?!p>|\/p>)[a-zA-Z][\s\S]*>/.test(trimmed);
  }

  function htmlTableToMarkdown(tableEl) {
    const rows = [];
    tableEl.querySelectorAll('tr').forEach((tr) => {
      const cells = Array.from(tr.querySelectorAll('td, th')).map((cell) => {
        return cell.textContent.trim().replace(/\|/g, '\\|');
      });
      rows.push(cells);
    });

    if (rows.length === 0) return '';

    const colCount = Math.max(...rows.map((row) => row.length));
    rows.forEach((row) => {
      while (row.length < colCount) row.push('');
    });

    const lines = [];
    lines.push('| ' + rows[0].join(' | ') + ' |');
    lines.push('| ' + rows[0].map(() => '---').join(' | ') + ' |');
    for (let i = 1; i < rows.length; i += 1) {
      lines.push('| ' + rows[i].join(' | ') + ' |');
    }

    return '\n' + lines.join('\n') + '\n\n';
  }

  // 轻量 HTML → Markdown 转换器，覆盖 Discourse 常见结构。
  function htmlToMarkdown(html) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');

    function walk(node) {
      if (node.nodeType === Node.TEXT_NODE) return node.textContent;
      if (node.nodeType !== Node.ELEMENT_NODE) return '';

      const tag = node.tagName.toLowerCase();
      const children = Array.from(node.childNodes).map(walk).join('');

      switch (tag) {
        case 'h1': return `\n# ${children.trim()}\n\n`;
        case 'h2': return `\n## ${children.trim()}\n\n`;
        case 'h3': return `\n### ${children.trim()}\n\n`;
        case 'h4': return `\n#### ${children.trim()}\n\n`;
        case 'h5': return `\n##### ${children.trim()}\n\n`;
        case 'h6': return `\n###### ${children.trim()}\n\n`;
        case 'p': return `\n${children.trim()}\n\n`;
        case 'br': return '\n';
        case 'hr': return '\n---\n\n';
        case 'strong':
        case 'b': {
          const text = children.trim();
          return text ? `**${text}**` : '';
        }
        case 'em':
        case 'i': {
          const text = children.trim();
          return text ? `*${text}*` : '';
        }
        case 'del':
        case 's': {
          const text = children.trim();
          return text ? `~~${text}~~` : '';
        }
        case 'code': {
          const text = children.trim();
          return text ? `\`${text}\`` : '';
        }
        case 'pre': {
          const codeEl = node.querySelector('code');
          const lang = codeEl?.className?.match(/lang-(\w+)/)?.[1] || '';
          const codeText = codeEl ? codeEl.textContent : node.textContent;
          return `\n\`\`\`${lang}\n${codeText.trim()}\n\`\`\`\n\n`;
        }
        case 'a': {
          const href = node.getAttribute('href') || '';
          const text = children.trim();
          if (!text) return '';
          return href && href !== text ? `[${text}](${href})` : text;
        }
        case 'img': {
          const src = node.getAttribute('src') || '';
          const alt = node.getAttribute('alt') || '';
          return src ? `![${alt}](${src})` : '';
        }
        case 'blockquote': {
          const lines = children.trim().split('\n').map((line) => `> ${line}`).join('\n');
          return `\n${lines}\n\n`;
        }
        case 'aside': {
          if (node.classList?.contains('quote')) {
            const titleEl = node.querySelector('.quote-controls, [data-username]');
            const quoteUser = node.getAttribute('data-username') || titleEl?.getAttribute('data-username') || '';
            const blockquote = node.querySelector(':scope > blockquote');
            const content = blockquote ? Array.from(blockquote.childNodes).map(walk).join('').trim() : children.trim();
            const attribution = quoteUser ? `**${quoteUser} said:**\n` : '';
            const lines = (attribution + content).split('\n').map((line) => `> ${line}`).join('\n');
            return `\n${lines}\n\n`;
          }
          return children;
        }
        case 'ul': {
          return '\n' + Array.from(node.children).map((li) => {
            return li.tagName?.toLowerCase() === 'li' ? `- ${walk(li).trim()}` : walk(li);
          }).join('\n') + '\n\n';
        }
        case 'ol': {
          return '\n' + Array.from(node.children).map((li, index) => {
            return li.tagName?.toLowerCase() === 'li' ? `${index + 1}. ${walk(li).trim()}` : walk(li);
          }).join('\n') + '\n\n';
        }
        case 'li': return children;
        case 'table': return htmlTableToMarkdown(node);
        case 'sup': return `<sup>${children}</sup>`;
        case 'sub': return `<sub>${children}</sub>`;
        case 'mark': return `==${children.trim()}==`;
        case 'span': {
          if (node.classList?.contains('mention')) return children.trim() || node.textContent.trim();
          return children;
        }
        case 'div': {
          if (node.classList?.contains('lightbox-wrapper')) {
            const img = node.querySelector('img');
            if (img) {
              const src = img.getAttribute('data-original-href') || img.getAttribute('src') || '';
              const alt = img.getAttribute('alt') || '';
              return src ? `\n![${alt}](${src})\n` : children;
            }
          }
          if (node.classList?.contains('onebox')) {
            const link = node.querySelector('a[href]');
            const title = node.querySelector('.onebox-body h3, .source a')?.textContent?.trim();
            const href = link?.getAttribute('href') || '';
            if (title && href) return `\n[${title}](${href})\n`;
          }
          return children;
        }
        case 'section':
        case 'article':
        case 'main':
        case 'nav':
        case 'header':
        case 'footer':
        case 'figure':
        case 'figcaption':
        case 'details':
        case 'summary':
        case 'dd':
        case 'dt':
        case 'dl':
        case 'abbr':
        case 'cite':
        case 'ins':
        case 'u':
          return children;
        default:
          return children;
      }
    }

    return walk(doc.body).replace(/\n{3,}/g, '\n\n').trim();
  }

  function ensureMarkdown(rawContent) {
    const trimmed = rawContent.trim();
    return isHtmlContent(trimmed) ? htmlToMarkdown(trimmed) : trimmed;
  }

  function normalizeDiscourseMd(md) {
    return md.replace(/!\[([^\]]+?)\|(\d+x\d+(?:x\d+)?(?:\|[^\]]*)?)\]\(/g, '![$1](');
  }

  namespace.markdown = {
    isHtmlContent,
    htmlToMarkdown,
    ensureMarkdown,
    normalizeDiscourseMd,
  };
})();


/* ===== src/content/discourse.js ===== */
/* Linux.do 工具箱 — Discourse 页面适配模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  function getTopicTitle() {
    return (
      document.querySelector('.fancy-title')?.textContent?.trim() ||
      document.querySelector('#topic-title h1')?.textContent?.trim() ||
      document.title.replace(/\s*[—–-]\s*Linux\.do\s*$/, '').trim() ||
      'Untitled'
    );
  }

  function getTopicUrl() {
    return window.location.origin + window.location.pathname;
  }

  function getTopicId() {
    const match = window.location.pathname.match(/\/t\/[^/]+\/(\d+)/);
    return match ? match[1] : null;
  }

  function getAllPostElements() {
    return Array.from(document.querySelectorAll('[data-post-id].topic-post, .topic-post'))
      .filter((postEl) => !postEl.closest('.ldtk-topic-article-pane'));
  }

  function getPostElements() {
    return getAllPostElements()
      .filter((postEl) => !postEl.closest('.ldtk-topic-native-stream'));
  }

  function getNativePostElements() {
    return getAllPostElements()
      .filter((postEl) => !postEl.classList.contains('ldtk-paged-comment'));
  }

  function getPostMeta(postEl) {
    const postId = postEl.getAttribute('data-post-id') || '';
    const postNumber = postEl.getAttribute('data-post-number') || '';
    const author =
      postEl.querySelector('.names .username')?.textContent?.trim() ||
      postEl.querySelector('.creator .username')?.textContent?.trim() ||
      'Unknown';
    const timeEl = postEl.querySelector('time');
    const date = timeEl?.getAttribute('datetime') || timeEl?.textContent?.trim() || '';
    return { postId, postNumber, author, date };
  }

  async function fetchRawPost(topicId, postNumber) {
    if (!topicId || !postNumber) throw new Error('缺少主题 ID 或楼层号');
    const res = await fetch(`/raw/${topicId}/${postNumber}`, { credentials: 'same-origin' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.text();
  }

  async function fetchTopicJson(topicId) {
    if (!topicId) throw new Error('缺少主题 ID');
    const res = await fetch(`/t/${topicId}.json`, {
      credentials: 'same-origin',
      headers: { Accept: 'application/json' },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return await res.json();
  }

  async function fetchPostsByIds(topicId, postIds) {
    if (!topicId) throw new Error('缺少主题 ID');
    if (!postIds.length) return [];

    const url = new URL(`/t/${topicId}/posts.json`, window.location.origin);
    postIds.forEach((postId) => {
      url.searchParams.append('post_ids[]', postId);
    });

    const res = await fetch(url.pathname + url.search, {
      credentials: 'same-origin',
      headers: { Accept: 'application/json' },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);

    const data = await res.json();
    return data?.post_stream?.posts || data?.posts || [];
  }

  function getPostImages(postEl) {
    const images = {};
    postEl.querySelectorAll('img[data-base62-sha1]').forEach((img) => {
      const src = img.getAttribute('src') || '';
      const sha1 = img.getAttribute('data-base62-sha1') || '';
      if (!sha1 || !src) return;

      const extMatch = src.match(/\.([a-zA-Z0-9]+)$/);
      const ext = extMatch ? extMatch[1] : 'png';
      images[`${sha1}.${ext}`] = src;
    });
    return images;
  }

  function replaceUploadUrls(rawMd, imageMap) {
    return rawMd.replace(/!\[([^\]]*)\]\(upload:\/\/([^)]+)\)/g, (match, alt, uploadFilename) => {
      if (imageMap[uploadFilename]) return `![${alt}](${imageMap[uploadFilename]})`;
      return match;
    });
  }

  namespace.discourse = {
    getTopicTitle,
    getTopicUrl,
    getTopicId,
    getAllPostElements,
    getPostElements,
    getNativePostElements,
    getPostMeta,
    fetchRawPost,
    fetchTopicJson,
    fetchPostsByIds,
    getPostImages,
    replaceUploadUrls,
  };
})();


/* ===== src/content/layout.js ===== */
/* Linux.do 工具箱 — 主题分栏布局模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  const BODY_CLASS = 'ldtk-topic-split-active';
  const WRAPPER_CLASS = 'ldtk-topic-split-wrapper';
  const ARTICLE_PANE_CLASS = 'ldtk-topic-article-pane';
  const ARTICLE_CLONE_CLASS = 'ldtk-topic-article-clone';
  const COMMENTS_PANE_CLASS = 'ldtk-topic-comments-pane';
  const COMMENTS_STREAM_CLASS = 'ldtk-topic-comments-stream';
  const HEADER_TITLE_CLASS = 'ldtk-topic-header-title';
  const HEADER_TITLE_INNER_CLASS = 'ldtk-topic-header-title-inner';
  const HEADER_META_CLASS = 'ldtk-topic-header-meta';
  const HEADER_META_INNER_CLASS = 'ldtk-topic-header-meta-inner';
  const ARTICLE_META_CLASS = 'ldtk-topic-article-meta';
  const ARTICLE_META_INNER_CLASS = 'ldtk-topic-article-meta-inner';
  const ARTICLE_ACTIONS_CLASS = 'ldtk-topic-article-actions';
  const FOOTER_ACTIONS_SOURCE_ATTR = 'data-ldtk-footer-actions-source';
  const FOOTER_ACTIONS_PLACEHOLDER_ATTR = 'data-ldtk-footer-actions-placeholder';
  const TOPIC_META_SOURCE_ATTR = 'data-ldtk-topic-meta-source';
  const NATIVE_STREAM_CLASS = 'ldtk-topic-native-stream';
  const ORIGINAL_MAIN_POST_CLASS = 'ldtk-topic-original-main-post';
  const PAGED_COMMENT_CLASS = 'ldtk-paged-comment';
  const PAGER_CLASS = 'ldtk-comments-pager';
  const PAGER_INFO_CLASS = 'ldtk-comments-pager-info';
  const PAGER_BUTTON_CLASS = 'ldtk-comments-pager-button';
  const PAGE_SIZE = 20;
  const TOPIC_META_SELECTORS = [
    '.topic-map',
    '.topic-map-expanded',
    '.topic-map__contents',
    '.topic-map-section',
    '.topic-map-summary',
    '.topic-map-stats',
    '.topic-map__stats',
    '.topic-stats',
  ];
  const FOOTER_ACTIONS_SELECTORS = '#topic-footer-buttons, .topic-footer-main-buttons';

  const pagerState = {
    topicId: '',
    page: 1,
    postIds: [],
    postsById: new Map(),
    loading: false,
  };

  let topicMetaObserver = null;
  let topicMetaSyncTimer = null;

  function getSplitWrapper(stream) {
    if (!stream?.parentElement) return null;
    if (stream.parentElement.classList.contains(WRAPPER_CLASS)) {
      return stream.parentElement;
    }

    const wrapper = document.createElement('div');
    wrapper.className = WRAPPER_CLASS;
    stream.parentElement.insertBefore(wrapper, stream);
    wrapper.appendChild(stream);
    return wrapper;
  }

  function getNativeStream() {
    return (
      document.querySelector(`.${NATIVE_STREAM_CLASS}`) ||
      document.querySelector('#post-stream') ||
      document.querySelector('.post-stream') ||
      document.querySelector('.topic-posts')
    );
  }

  function updateSplitPaneHeight(wrapper) {
    if (!wrapper) return;

    const viewportHeight = window.visualViewport?.height || window.innerHeight;
    const wrapperTop = Math.max(0, wrapper.getBoundingClientRect().top);
    const height = Math.max(320, viewportHeight - wrapperTop - 8);
    wrapper.style.setProperty('--ldtk-split-pane-height', `${height}px`);
  }

  function getHeaderTitleMount() {
    return (
      document.querySelector('.d-header .contents') ||
      document.querySelector('header.d-header .contents') ||
      document.querySelector('.d-header')
    );
  }

  function stripHeaderCloneUnsafeNodes(clone) {
    clone.querySelectorAll([
      'script',
      'style',
      '.edit-topic',
      '.topic-statuses',
      '.topic-notifications-button',
    ].join(',')).forEach((el) => el.remove());

    clone.querySelectorAll('[id]').forEach((el) => {
      el.removeAttribute('id');
    });
  }

  function findTopicMetaSource() {
    const directMatch = Array.from(document.querySelectorAll(TOPIC_META_SELECTORS.join(','))).find((el) => (
      !el.closest(`.${HEADER_META_CLASS}`) &&
      !el.closest(`.${ARTICLE_PANE_CLASS}`) &&
      !el.closest(`.${COMMENTS_PANE_CLASS}`)
    ));

    if (directMatch) return directMatch;

    return Array.from(document.querySelectorAll('#main-outlet .container.posts > .row > *, .topic-area > *')).find((el) => {
      if (
        el.closest(`.${HEADER_META_CLASS}`) ||
        el.closest(`.${ARTICLE_PANE_CLASS}`) ||
        el.closest(`.${COMMENTS_PANE_CLASS}`) ||
        el.matches('#topic-title')
      ) {
        return false;
      }

      const text = el.textContent || '';
      const hasStatsText = ['浏览量', '赞', '链接', '用户'].filter((label) => text.includes(label)).length >= 2;
      const hasAvatars = el.querySelectorAll('img.avatar, .avatar').length >= 2;
      const hasSummary = Boolean(el.querySelector('[title*="总结"], button, .btn'));
      return hasStatsText && (hasAvatars || hasSummary);
    });
  }

  function stripHeaderMetaCloneUnsafeNodes(clone) {
    clone.querySelectorAll([
      'script',
      'style',
      '[id]',
    ].join(',')).forEach((el) => {
      if (el.matches('script, style')) {
        el.remove();
        return;
      }
      el.removeAttribute('id');
    });
  }

  function syncSplitHeaderMeta(mount, headerTitle) {
    const source = findTopicMetaSource();
    if (!source || !mount) return;

    document.querySelectorAll(`[${TOPIC_META_SOURCE_ATTR}]`).forEach((el) => {
      if (el !== source) el.removeAttribute(TOPIC_META_SOURCE_ATTR);
    });
    source.setAttribute(TOPIC_META_SOURCE_ATTR, 'true');

    let headerMeta = mount.querySelector(`:scope > .${HEADER_META_CLASS}`);

    if (!headerMeta) {
      headerMeta = document.createElement('div');
      headerMeta.className = HEADER_META_CLASS;

      if (headerTitle?.parentElement === mount) {
        headerTitle.insertAdjacentElement('afterend', headerMeta);
      } else {
        mount.insertBefore(headerMeta, mount.children[2] || null);
      }
    }

    headerMeta.replaceChildren(buildTopicMetaClone(source, HEADER_META_INNER_CLASS));
  }

  function buildTopicMetaClone(source, innerClass) {
    const clone = source.cloneNode(true);
    clone.classList.add(innerClass);
    clone.removeAttribute('id');
    clone.removeAttribute(TOPIC_META_SOURCE_ATTR);
    stripHeaderMetaCloneUnsafeNodes(clone);
    return clone;
  }

  function syncArticleTopicMeta(pane) {
    if (!pane) return;

    const source = findTopicMetaSource();
    let articleMeta = pane.querySelector(`:scope > .${ARTICLE_META_CLASS}`);

    if (!source) {
      articleMeta?.remove();
      return;
    }

    if (!articleMeta) {
      articleMeta = document.createElement('section');
      articleMeta.className = ARTICLE_META_CLASS;
      articleMeta.setAttribute('aria-label', '主题统计与操作');
      pane.appendChild(articleMeta);
    }

    articleMeta.replaceChildren(buildTopicMetaClone(source, ARTICLE_META_INNER_CLASS));
  }

  function findFooterActionsSource() {
    return Array.from(document.querySelectorAll(FOOTER_ACTIONS_SELECTORS)).find((el) => (
      !el.closest(`.${ARTICLE_PANE_CLASS}`) &&
      !el.closest(`.${HEADER_META_CLASS}`) &&
      !el.closest(`.${COMMENTS_PANE_CLASS}`)
    ));
  }

  function ensureFooterActionsPlaceholder(source) {
    const existing = document.querySelector(`[${FOOTER_ACTIONS_PLACEHOLDER_ATTR}="true"]`);
    if (existing) return existing;

    const placeholder = document.createElement('span');
    placeholder.hidden = true;
    placeholder.setAttribute(FOOTER_ACTIONS_PLACEHOLDER_ATTR, 'true');
    source.parentElement?.insertBefore(placeholder, source);
    return placeholder;
  }

  function syncArticleFooterActions(pane) {
    if (!pane) return;

    const movedSource = pane.querySelector(`:scope > .${ARTICLE_ACTIONS_CLASS} > [${FOOTER_ACTIONS_SOURCE_ATTR}="true"]`);
    const source = movedSource || findFooterActionsSource();
    let articleActions = pane.querySelector(`:scope > .${ARTICLE_ACTIONS_CLASS}`);

    if (!source) {
      articleActions?.remove();
      return;
    }

    if (!articleActions) {
      articleActions = document.createElement('section');
      articleActions.className = ARTICLE_ACTIONS_CLASS;
      articleActions.setAttribute('aria-label', '主题操作');
      pane.appendChild(articleActions);
    }

    if (!movedSource) {
      ensureFooterActionsPlaceholder(source);
      source.setAttribute(FOOTER_ACTIONS_SOURCE_ATTR, 'true');
      articleActions.appendChild(source);
    }
  }

  function restoreFooterActions() {
    const source = document.querySelector(`[${FOOTER_ACTIONS_SOURCE_ATTR}="true"]`);
    const placeholder = document.querySelector(`[${FOOTER_ACTIONS_PLACEHOLDER_ATTR}="true"]`);

    if (source) {
      source.removeAttribute(FOOTER_ACTIONS_SOURCE_ATTR);
      if (placeholder?.parentElement) {
        placeholder.parentElement.insertBefore(source, placeholder);
      }
    }

    placeholder?.remove();
    document.querySelectorAll(`.${ARTICLE_ACTIONS_CLASS}`).forEach((el) => el.remove());
  }

  function syncSplitHeaderTitle() {
    const source = document.querySelector('#topic-title');
    const mount = getHeaderTitleMount();
    if (!source || !mount) return;

    let headerTitle = mount.querySelector(`:scope > .${HEADER_TITLE_CLASS}`);

    if (!headerTitle) {
      headerTitle = document.createElement('div');
      headerTitle.className = HEADER_TITLE_CLASS;

      const logoArea = mount.querySelector(':scope > .title, :scope > .home-logo-wrapper, :scope > .brand-header');
      if (logoArea) {
        logoArea.insertAdjacentElement('afterend', headerTitle);
      } else {
        mount.insertBefore(headerTitle, mount.children[1] || null);
      }
    }

    const clone = source.cloneNode(true);
    clone.className = HEADER_TITLE_INNER_CLASS;
    stripHeaderCloneUnsafeNodes(clone);
    headerTitle.replaceChildren(clone);
    syncSplitHeaderMeta(mount, headerTitle);
  }

  function syncSplitTopicMeta() {
    syncSplitHeaderTitle();
    document.querySelectorAll(`.${ARTICLE_PANE_CLASS}`).forEach((pane) => {
      syncArticleTopicMeta(pane);
      syncArticleFooterActions(pane);
    });
  }

  function scheduleSplitHeaderSync() {
    syncSplitTopicMeta();
    [100, 350, 800, 1500, 3000].forEach((delay) => {
      setTimeout(syncSplitTopicMeta, delay);
    });
  }

  function scheduleTopicMetaSync(delay = 80) {
    if (topicMetaSyncTimer) clearTimeout(topicMetaSyncTimer);
    topicMetaSyncTimer = setTimeout(() => {
      topicMetaSyncTimer = null;
      syncSplitTopicMeta();
    }, delay);
  }

  function isNativeTopicMetaNode(node) {
    if (node.nodeType !== Node.ELEMENT_NODE) return false;

    if (
      node.closest?.(`.${HEADER_META_CLASS}`) ||
      node.closest?.(`.${ARTICLE_PANE_CLASS}`) ||
      node.closest?.(`.${COMMENTS_PANE_CLASS}`)
    ) {
      return false;
    }

    const selectors = TOPIC_META_SELECTORS.join(',');
    return node.matches?.(selectors) || Boolean(node.querySelector?.(selectors));
  }

  function bindTopicMetaObserver() {
    if (topicMetaObserver) return;

    const target = document.querySelector('#main-outlet, #main, body') || document.body;
    topicMetaObserver = new MutationObserver((mutations) => {
      const shouldSync = mutations.some((mutation) => {
        const nodes = [
          mutation.target,
          ...Array.from(mutation.addedNodes || []),
          ...Array.from(mutation.removedNodes || []),
        ];

        return nodes.some(isNativeTopicMetaNode);
      });

      if (shouldSync) scheduleTopicMetaSync();
    });

    topicMetaObserver.observe(target, {
      childList: true,
      subtree: true,
      characterData: true,
    });
  }

  function restoreSplitHeaderTitle() {
    if (topicMetaSyncTimer) {
      clearTimeout(topicMetaSyncTimer);
      topicMetaSyncTimer = null;
    }

    if (topicMetaObserver) {
      topicMetaObserver.disconnect();
      topicMetaObserver = null;
    }

    document.querySelectorAll(`.${HEADER_TITLE_CLASS}`).forEach((el) => el.remove());
    document.querySelectorAll(`.${HEADER_META_CLASS}`).forEach((el) => el.remove());
    document.querySelectorAll(`.${ARTICLE_META_CLASS}`).forEach((el) => el.remove());
    restoreFooterActions();
    document.querySelectorAll(`[${TOPIC_META_SOURCE_ATTR}]`).forEach((el) => {
      el.removeAttribute(TOPIC_META_SOURCE_ATTR);
    });
  }

  function stripCloneUnsafeNodes(clone) {
    clone.querySelectorAll([
      '.ldcopy-actions',
      '.topic-map',
      '.embedded-posts',
      'script',
      'style',
    ].join(',')).forEach((el) => el.remove());

    clone.querySelectorAll('[id]').forEach((el) => {
      el.removeAttribute('id');
    });
  }

  function buildArticleClone(mainPost) {
    const clone = mainPost.cloneNode(true);
    clone.classList.add(ARTICLE_CLONE_CLASS);
    clone.classList.remove(ORIGINAL_MAIN_POST_CLASS);
    clone.removeAttribute('id');
    stripCloneUnsafeNodes(clone);
    return clone;
  }

  function ensureArticlePane(wrapper, stream) {
    let pane = wrapper.querySelector(`:scope > .${ARTICLE_PANE_CLASS}`);

    if (!pane) {
      pane = document.createElement('aside');
      pane.className = ARTICLE_PANE_CLASS;
      pane.setAttribute('aria-label', '文章内容');
      wrapper.insertBefore(pane, stream);
    }

    return pane;
  }

  function ensureCommentsPane(wrapper) {
    let pane = wrapper.querySelector(`:scope > .${COMMENTS_PANE_CLASS}`);

    if (!pane) {
      pane = document.createElement('section');
      pane.className = COMMENTS_PANE_CLASS;
      pane.setAttribute('aria-label', '评论分页');
      wrapper.appendChild(pane);
    }

    pane.classList.remove(COMMENTS_STREAM_CLASS);
    return pane;
  }

  function ensureCommentsStream(pane) {
    let stream = pane.querySelector(`:scope > .${COMMENTS_STREAM_CLASS}`);

    if (!stream) {
      stream = document.createElement('div');
      stream.className = COMMENTS_STREAM_CLASS;
      pane.insertBefore(stream, pane.firstChild);
    }

    Array.from(pane.children).forEach((child) => {
      if (
        child !== stream &&
        !child.classList.contains(PAGER_CLASS)
      ) {
        stream.appendChild(child);
      }
    });

    return stream;
  }

  function syncArticlePane(pane, mainPost) {
    const postId = mainPost.getAttribute('data-post-id') || '';
    const currentPostId = pane.getAttribute('data-source-post-id') || '';

    if (currentPostId !== postId || !pane.querySelector(`.${ARTICLE_CLONE_CLASS}`)) {
      restoreFooterActions();
      pane.replaceChildren(buildArticleClone(mainPost));
      pane.setAttribute('data-source-post-id', postId);
    }

    syncArticleTopicMeta(pane);
    syncArticleFooterActions(pane);
  }

  function showArticleLoading(pane) {
    if (pane.querySelector(`.${ARTICLE_CLONE_CLASS}`)) return;
    restoreFooterActions();
    const placeholder = document.createElement('div');
    placeholder.className = ARTICLE_CLONE_CLASS;
    placeholder.textContent = '正在加载正文...';
    pane.replaceChildren(placeholder);
    pane.removeAttribute('data-source-post-id');
  }

  function restoreTopicSplitLayout() {
    document.body.classList.remove(BODY_CLASS);
    restoreSplitHeaderTitle();

    document.querySelectorAll(`.${ARTICLE_PANE_CLASS}`).forEach((pane) => pane.remove());
    document.querySelectorAll(`.${COMMENTS_PANE_CLASS}`).forEach((pane) => pane.remove());
    document.querySelectorAll(`.${PAGER_CLASS}`).forEach((pager) => pager.remove());
    document.querySelectorAll(`.${PAGED_COMMENT_CLASS}`).forEach((postEl) => postEl.remove());
    document.querySelectorAll(`.${NATIVE_STREAM_CLASS}`).forEach((stream) => {
      stream.classList.remove(NATIVE_STREAM_CLASS);
      stream.removeAttribute('aria-hidden');
      if (stream.parentElement?.classList.contains(WRAPPER_CLASS)) {
        stream.parentElement.parentElement?.insertBefore(stream, stream.parentElement);
      }
    });
    document.querySelectorAll(`.${WRAPPER_CLASS}`).forEach((wrapper) => {
      if (!wrapper.children.length) wrapper.remove();
      else wrapper.classList.remove(WRAPPER_CLASS);
    });
    document.querySelectorAll(`.${COMMENTS_STREAM_CLASS}`).forEach((stream) => stream.classList.remove(COMMENTS_STREAM_CLASS));
    document.querySelectorAll(`.${ORIGINAL_MAIN_POST_CLASS}`).forEach((postEl) => {
      postEl.classList.remove(ORIGINAL_MAIN_POST_CLASS);
      postEl.removeAttribute('aria-hidden');
    });
  }

  function resetPager(topicId) {
    pagerState.topicId = topicId || '';
    pagerState.page = 1;
    pagerState.postIds = [];
    pagerState.postsById.clear();
    pagerState.loading = false;
    document.querySelectorAll(`.${COMMENTS_PANE_CLASS}`).forEach((stream) => {
      stream.removeAttribute('data-ldtk-pager-topic-id');
      stream.removeAttribute('data-ldtk-pager-page');
      stream.removeAttribute('data-ldtk-pager-key');
    });
  }

  function getTotalPages() {
    return Math.max(1, Math.ceil(Math.max(0, pagerState.postIds.length - 1) / PAGE_SIZE));
  }

  function shouldShowPager() {
    return getTotalPages() > 1;
  }

  function getPagePostIds(page) {
    const commentIds = pagerState.postIds.slice(1);
    const start = (page - 1) * PAGE_SIZE;
    return commentIds.slice(start, start + PAGE_SIZE);
  }

  function getPageKey(page = pagerState.page) {
    return getPagePostIds(page).join(',');
  }

  function isCurrentPageRendered(stream) {
    return (
      stream.getAttribute('data-ldtk-pager-topic-id') === pagerState.topicId &&
      stream.getAttribute('data-ldtk-pager-page') === String(pagerState.page) &&
      stream.getAttribute('data-ldtk-pager-key') === getPageKey()
    );
  }

  function setPagerStatus(stream, text, isError = false) {
    const infoEl = stream.parentElement?.querySelector(`.${PAGER_INFO_CLASS}`);
    if (!infoEl) return;
    infoEl.textContent = text;
    infoEl.classList.toggle('is-error', isError);
  }

  function updatePagerButtons(stream) {
    const totalPages = getTotalPages();
    const prevBtn = stream.parentElement?.querySelector('[data-ldtk-pager-action="prev"]');
    const nextBtn = stream.parentElement?.querySelector('[data-ldtk-pager-action="next"]');

    if (prevBtn) prevBtn.disabled = pagerState.loading || pagerState.page <= 1;
    if (nextBtn) nextBtn.disabled = pagerState.loading || pagerState.page >= totalPages;
  }

  function removePager(stream) {
    stream.parentElement?.querySelector(`:scope > .${PAGER_CLASS}`)?.remove();
  }

  function resetCommentsScroll(stream) {
    // 分页切换后立即回到评论栏顶部，避免平滑滚动带来的等待感。
    stream.scrollTop = 0;
  }

  function escapeHtml(value) {
    return String(value ?? '').replace(/[&<>"']/g, (char) => ({
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#39;',
    }[char]));
  }

  function escapeAttr(value) {
    return escapeHtml(value).replace(/`/g, '&#96;');
  }

  function createPostFromJson(post) {
    const article = document.createElement('article');
    article.className = `topic-post ${PAGED_COMMENT_CLASS}`;
    article.setAttribute('data-post-id', String(post.id || ''));
    article.setAttribute('data-post-number', String(post.post_number || ''));

    const avatar = post.avatar_template
      ? post.avatar_template.replace('{size}', '45')
      : '';
    const createdAt = post.created_at || '';
    const cooked = post.cooked || '';

    article.innerHTML = `
      <div class="topic-avatar">
        ${avatar ? `<img class="avatar" width="45" height="45" src="${escapeAttr(avatar)}" alt="">` : ''}
      </div>
      <div class="topic-body">
        <div class="topic-meta-data">
          <span class="names">
            <span class="username">${escapeHtml(post.username || 'Unknown')}</span>
          </span>
          ${createdAt ? `<a class="post-date" href="#post-${escapeAttr(post.post_number || '')}"><time datetime="${escapeAttr(createdAt)}">${escapeHtml(createdAt.slice(0, 10))}</time></a>` : ''}
        </div>
        <div class="cooked">${cooked}</div>
        <section class="post-menu-area">
          <nav class="post-controls"></nav>
        </section>
      </div>
    `;

    return article;
  }

  function removePagedComments(stream) {
    stream.querySelectorAll(`:scope > .${PAGED_COMMENT_CLASS}`).forEach((postEl) => postEl.remove());
  }

  function renderCurrentPage(stream) {
    removePagedComments(stream);

    const postIds = getPagePostIds(pagerState.page);
    const fragment = document.createDocumentFragment();

    postIds.forEach((postId) => {
      const post = pagerState.postsById.get(Number(postId));
      if (post) fragment.appendChild(createPostFromJson(post));
    });

    stream.appendChild(fragment);

    const totalPages = getTotalPages();
    const commentCount = Math.max(0, pagerState.postIds.length - 1);
    stream.setAttribute('data-ldtk-pager-topic-id', pagerState.topicId);
    stream.setAttribute('data-ldtk-pager-page', String(pagerState.page));
    stream.setAttribute('data-ldtk-pager-key', getPageKey());

    if (!shouldShowPager()) {
      removePager(stream);
      return;
    }

    ensurePager(stream);
    setPagerStatus(stream, `第 ${pagerState.page} / ${totalPages} 页，共 ${commentCount} 条评论`);
    updatePagerButtons(stream);
  }

  async function loadPage(stream, page) {
    const totalPages = getTotalPages();
    const nextPage = Math.min(Math.max(1, page), totalPages);
    const shouldResetScroll = nextPage !== pagerState.page;
    const postIds = getPagePostIds(nextPage);
    const missingIds = postIds.filter((postId) => !pagerState.postsById.has(Number(postId)));

    pagerState.loading = true;
    if (shouldShowPager()) {
      ensurePager(stream);
      updatePagerButtons(stream);
      setPagerStatus(stream, '正在加载评论...');
    } else {
      removePager(stream);
    }

    try {
      if (missingIds.length) {
        const { discourse } = namespace;
        const posts = await discourse.fetchPostsByIds(pagerState.topicId, missingIds);
        posts.forEach((post) => {
          if (post?.id) pagerState.postsById.set(Number(post.id), post);
        });
      }

      pagerState.page = nextPage;
      renderCurrentPage(stream);
      if (shouldResetScroll) resetCommentsScroll(stream);
      namespace.buttons?.injectButtons?.();
    } catch (err) {
      setPagerStatus(stream, `评论加载失败：${err?.message || '未知错误'}`, true);
    } finally {
      pagerState.loading = false;
      updatePagerButtons(stream);
    }
  }

  function ensurePager(stream) {
    const pane = stream.parentElement;
    if (!pane) return null;

    let pager = pane.querySelector(`:scope > .${PAGER_CLASS}`);

    if (!pager) {
      pager = document.createElement('nav');
      pager.className = PAGER_CLASS;
      pager.setAttribute('aria-label', '评论分页');
      pager.innerHTML = `
        <button class="${PAGER_BUTTON_CLASS}" type="button" data-ldtk-pager-action="prev">上一页</button>
        <span class="${PAGER_INFO_CLASS}">正在加载评论...</span>
        <button class="${PAGER_BUTTON_CLASS}" type="button" data-ldtk-pager-action="next">下一页</button>
      `;

      pager.addEventListener('click', (event) => {
        const button = event.target.closest('[data-ldtk-pager-action]');
        if (!button || pagerState.loading) return;

        const action = button.getAttribute('data-ldtk-pager-action');
        loadPage(stream, pagerState.page + (action === 'next' ? 1 : -1));
      });

      pane.appendChild(pager);
    }

    return pager;
  }

  async function ensureCommentPager(stream, topicId) {
    if (pagerState.topicId !== topicId) resetPager(topicId);

    if (!pagerState.postIds.length && !pagerState.loading) {
      pagerState.loading = true;

      try {
        const { discourse } = namespace;
        const topic = await discourse.fetchTopicJson(topicId);
        pagerState.postIds = topic?.post_stream?.stream || [];
        (topic?.post_stream?.posts || []).forEach((post) => {
          if (post?.id) pagerState.postsById.set(Number(post.id), post);
        });
      } catch (err) {
        ensurePager(stream);
        setPagerStatus(stream, `评论初始化失败：${err?.message || '未知错误'}`, true);
        return;
      } finally {
        pagerState.loading = false;
      }
    }

    if (!pagerState.postIds.length) {
      removePager(stream);
      return;
    }

    if (!stream.querySelector(`:scope > .${PAGED_COMMENT_CLASS}`)) {
      await loadPage(stream, pagerState.page);
    } else if (isCurrentPageRendered(stream)) {
      const totalPages = getTotalPages();
      const commentCount = Math.max(0, pagerState.postIds.length - 1);
      if (!shouldShowPager()) {
        removePager(stream);
        return;
      }

      ensurePager(stream);
      setPagerStatus(stream, `第 ${pagerState.page} / ${totalPages} 页，共 ${commentCount} 条评论`);
      updatePagerButtons(stream);
    } else {
      renderCurrentPage(stream);
    }
  }

  async function loadTopicSnapshot(topicId) {
    const { discourse } = namespace;
    const topic = await discourse.fetchTopicJson(topicId);
    const posts = topic?.post_stream?.posts || [];
    pagerState.postIds = topic?.post_stream?.stream || posts.map((post) => post.id).filter(Boolean);
    posts.forEach((post) => {
      if (post?.id) pagerState.postsById.set(Number(post.id), post);
    });
    return topic;
  }

  function getNativeMainPost(nativeStream) {
    return (
      nativeStream?.querySelector?.('[data-post-number="1"].topic-post, .topic-post[data-post-number="1"]') ||
      nativeStream?.querySelector?.('[data-post-id].topic-post, .topic-post') ||
      null
    );
  }

  async function ensureSplitFromTopic(wrapper, nativeStream, topicId) {
    const articlePane = ensureArticlePane(wrapper, nativeStream);
    const commentsPane = ensureCommentsPane(wrapper);
    const commentsStream = ensureCommentsStream(commentsPane);

    document.body.classList.add(BODY_CLASS);
    scheduleSplitHeaderSync();
    bindTopicMetaObserver();
    nativeStream.classList.add(NATIVE_STREAM_CLASS);
    nativeStream.setAttribute('aria-hidden', 'true');
    showArticleLoading(articlePane);
    updateSplitPaneHeight(wrapper);

    try {
      if (pagerState.topicId !== topicId || !pagerState.postIds.length) {
        resetPager(topicId);
        await loadTopicSnapshot(topicId);
      }

      const firstPost = pagerState.postsById.get(Number(pagerState.postIds[0]));
      const mainPost = getNativeMainPost(nativeStream) || (firstPost ? createPostFromJson(firstPost) : null);
      if (!mainPost) throw new Error('未找到主题正文');

      syncArticlePane(articlePane, mainPost);
      updateSplitPaneHeight(wrapper);
      await ensureCommentPager(commentsStream, topicId);
      updateSplitPaneHeight(wrapper);
      setTimeout(() => updateSplitPaneHeight(wrapper), 250);
    } catch (err) {
      // 任何接口或 DOM 适配异常都回退到站点原生布局，避免留下半初始化页面。
      restoreTopicSplitLayout();
      throw err;
    }
  }

  async function applyTopicSplitLayout() {
    const { discourse, settings: settingsApi } = namespace;
    const settings = await settingsApi.getSettings();
    const topicId = discourse.getTopicId();

    if (!settings.enableSplitLayout || !topicId) {
      restoreTopicSplitLayout();
      return;
    }

    const stream = getNativeStream();
    const wrapper = getSplitWrapper(stream);
    if (!stream || !wrapper) return;

    await ensureSplitFromTopic(wrapper, stream, topicId);
  }

  window.addEventListener('resize', () => {
    document.querySelectorAll(`.${WRAPPER_CLASS}`).forEach(updateSplitPaneHeight);
  });

  namespace.layout = {
    applyTopicSplitLayout,
    restoreTopicSplitLayout,
  };
})();


/* ===== src/content/output.js ===== */
/* Linux.do 工具箱 — 输出与反馈模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  function formatPostMd(meta, rawMd, title, url, options = {}) {
    if (options.includeMetadata === false) return rawMd.trim();

    const sourceUrl = url + (meta.postNumber ? '#post-' + meta.postNumber : '');
    const header = `<!-- 来源: ${sourceUrl} | 作者: ${meta.author}${meta.date ? ' | ' + meta.date : ''} -->`;
    return header + '\n\n' + rawMd.trim();
  }

  function formatTopicMd(posts, title, url, options = {}) {
    if (options.includeMetadata === false) {
      return posts.map((post) => post.raw.trim()).join('\n\n---\n\n');
    }

    const lines = [`<!-- 来源: ${url} -->`, ''];
    posts.forEach((post, index) => {
      const postNumber = post.meta.postNumber || index + 1;
      const postUrl = `${url}#post-${postNumber}`;
      lines.push(`<!-- #${postNumber} ${post.meta.author} | ${postUrl} -->`);
      lines.push('');
      lines.push(post.raw.trim());
      lines.push('');
    });
    return lines.join('\n');
  }

  function copyToClipboard(text) {
    return navigator.clipboard.writeText(text);
  }

  function downloadFile(content, filename) {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  }

  function sanitizeFilename(name) {
    return name.replace(/[<>:"/\\|?*\n\r]/g, '_').replace(/\s+/g, ' ').substring(0, 80);
  }

  function showToast(message) {
    let toast = document.getElementById('ldcopy-toast');
    if (!toast) {
      toast = document.createElement('div');
      toast.id = 'ldcopy-toast';
      document.body.appendChild(toast);
    }

    if (toast.hideTimer) clearTimeout(toast.hideTimer);
    toast.textContent = message;
    toast.className = 'ldcopy-toast ldcopy-toast-show';
    toast.hideTimer = setTimeout(() => {
      toast.className = 'ldcopy-toast';
      toast.hideTimer = null;
    }, 2500);
  }

  namespace.output = {
    formatPostMd,
    formatTopicMd,
    copyToClipboard,
    downloadFile,
    sanitizeFilename,
    showToast,
  };
})();


/* ===== src/content/post-export.js ===== */
/* Linux.do 工具箱 — 楼层导出流程模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  async function buildPostMarkdown(postEl, settings) {
    const { discourse, markdown, output } = namespace;
    const topicId = discourse.getTopicId();
    const meta = discourse.getPostMeta(postEl);
    const raw = await discourse.fetchRawPost(topicId, meta.postNumber);
    const normalized = markdown.normalizeDiscourseMd(raw);
    const processedRaw = settings.replaceUploadUrls === false
      ? normalized
      : discourse.replaceUploadUrls(normalized, discourse.getPostImages(postEl));
    const md = markdown.ensureMarkdown(processedRaw);

    return {
      meta,
      markdown: output.formatPostMd(
        meta,
        md,
        discourse.getTopicTitle(),
        discourse.getTopicUrl(),
        settings,
      ),
      raw: md,
    };
  }

  function getFallbackMeta(postEl, index) {
    try {
      return namespace.discourse.getPostMeta(postEl);
    } catch {
      return { postId: '', postNumber: String(index + 1), author: 'Unknown', date: '' };
    }
  }

  async function collectLoadedPosts(settings) {
    const { discourse } = namespace;
    const postEls = Array.from(discourse.getPostElements());
    const posts = [];
    const failures = [];

    for (const [index, postEl] of postEls.entries()) {
      try {
        const result = await buildPostMarkdown(postEl, settings);
        posts.push({ meta: result.meta, raw: result.raw });
      } catch (err) {
        const meta = getFallbackMeta(postEl, index);
        failures.push({
          meta,
          error: err?.message || '未知错误',
        });
      }
    }

    return {
      posts,
      failures,
      total: postEls.length,
      successCount: posts.length,
      failureCount: failures.length,
    };
  }

  async function getAllPostsRaw(settings) {
    const result = await collectLoadedPosts(settings);
    return result.posts;
  }

  namespace.postExport = {
    buildPostMarkdown,
    collectLoadedPosts,
    getAllPostsRaw,
  };
})();


/* ===== src/content/buttons.js ===== */
/* Linux.do 工具箱 — 页面按钮注入模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  const COPY_ICON = '<svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor"><path d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z"/></svg>';
  const DOWNLOAD_ICON = '<svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor"><path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z"/></svg>';

  function removeInjectedActions() {
    document.querySelectorAll('.ldcopy-actions').forEach((el) => el.remove());
  }

  async function injectButtons() {
    const { discourse, output, postExport, settings: settingsApi } = namespace;
    const settings = await settingsApi.getSettings();

    if (!settings.enablePostActions) {
      removeInjectedActions();
      return;
    }

    discourse.getPostElements().forEach((postEl) => {
      if (postEl.querySelector('.ldcopy-actions')) return;

      const actionsEl = postEl.querySelector('.post-controls, .actions');
      if (!actionsEl) return;

      const wrapper = document.createElement('div');
      wrapper.className = 'ldcopy-actions';

      const copyBtn = document.createElement('button');
      copyBtn.className = 'ldcopy-btn';
      copyBtn.title = '复制本楼原始 Markdown';
      copyBtn.innerHTML = `${COPY_ICON} <span>复制</span>`;
      copyBtn.addEventListener('click', async (event) => {
        event.preventDefault();
        event.stopPropagation();
        copyBtn.disabled = true;
        try {
          const latestSettings = await settingsApi.getSettings();
          const result = await postExport.buildPostMarkdown(postEl, latestSettings);
          await output.copyToClipboard(result.markdown);
          output.showToast('✅ 已复制到剪贴板');
        } catch (err) {
          output.showToast('❌ 失败: ' + err.message);
        } finally {
          copyBtn.disabled = false;
        }
      });

      const downloadBtn = document.createElement('button');
      downloadBtn.className = 'ldcopy-btn';
      downloadBtn.title = '下载本楼为 Markdown 文件';
      downloadBtn.innerHTML = `${DOWNLOAD_ICON} <span>下载</span>`;
      downloadBtn.addEventListener('click', async (event) => {
        event.preventDefault();
        event.stopPropagation();
        downloadBtn.disabled = true;
        try {
          const latestSettings = await settingsApi.getSettings();
          const result = await postExport.buildPostMarkdown(postEl, latestSettings);
          const title = discourse.getTopicTitle();
          const filename = output.sanitizeFilename(`${title}_#${result.meta.postNumber || 'post'}.md`);
          output.downloadFile(result.markdown, filename);
          output.showToast(`✅ 已下载 ${filename}`);
        } catch (err) {
          output.showToast('❌ 失败: ' + err.message);
        } finally {
          downloadBtn.disabled = false;
        }
      });

      wrapper.appendChild(copyBtn);
      wrapper.appendChild(downloadBtn);
      actionsEl.appendChild(wrapper);
    });
  }

  namespace.buttons = {
    injectButtons,
    removeInjectedActions,
  };
})();


/* ===== src/content/base64.js ===== */
/* Linux.do 工具箱 — Base64 选择工具模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  function decodeBase64Utf8(text) {
    const normalized = text.replace(/\s+/g, '');
    const binary = atob(normalized);
    const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));

    try {
      return new TextDecoder('utf-8', { fatal: true }).decode(bytes);
    } catch {
      // 兼容非 UTF-8 或历史内容，尽量给出可读结果。
      return binary;
    }
  }

  function stripChineseText(text) {
    return text.replace(/[\p{Script=Han}\u3000-\u303f\uff01-\uff60]/gu, '');
  }

  function getSelectedText() {
    return window.getSelection().toString().trim();
  }

  function styleSelectionToolButton(button, order) {
    button.style.cssText = [
      'margin-right: 4px',
      'padding: 4px 8px',
      'font-size: 13px',
      `order: ${order}`,
      'display: inline-flex',
      'align-items: center',
    ].join('; ');
  }

  async function injectBase64Button() {
    const { output, settings: settingsApi } = namespace;
    const settings = await settingsApi.getSettings();
    if (!settings.enableBase64Decode) {
      document.querySelectorAll('.ldcopy-base64-btn, .ldcopy-strip-chinese-btn').forEach((el) => el.remove());
      return;
    }

    const quoteContainer = document.querySelector('.quote-button');
    if (!quoteContainer) return;

    let base64Btn = quoteContainer.querySelector('.ldcopy-base64-btn');
    if (!base64Btn) {
      base64Btn = document.createElement('button');
      base64Btn.className = 'btn btn-flat ldcopy-base64-btn';
      base64Btn.title = 'Base64 解码并复制';
      base64Btn.innerHTML = '<svg viewBox="0 0 24 24" width="14" height="14" fill="currentColor" style="vertical-align: middle; margin-right: 2px;"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>base64';
      styleSelectionToolButton(base64Btn, -2);

      base64Btn.addEventListener('click', async (event) => {
        event.preventDefault();
        event.stopPropagation();
        try {
          const selectedText = getSelectedText();
          if (!selectedText) {
            output.showToast('❌ 未选中文字');
            return;
          }
          await output.copyToClipboard(decodeBase64Utf8(selectedText));
          output.showToast('✅ Base64 解码已复制');
        } catch (err) {
          output.showToast('❌ Base64 解码失败: ' + err.message);
        }
      });

      quoteContainer.insertBefore(base64Btn, quoteContainer.firstChild);
    }

    if (!quoteContainer.querySelector('.ldcopy-strip-chinese-btn')) {
      const stripChineseBtn = document.createElement('button');
      stripChineseBtn.className = 'btn btn-flat ldcopy-strip-chinese-btn';
      stripChineseBtn.title = '去掉选中文本中的中文并复制';
      stripChineseBtn.textContent = '去中文';
      styleSelectionToolButton(stripChineseBtn, -1);

      stripChineseBtn.addEventListener('click', async (event) => {
        event.preventDefault();
        event.stopPropagation();
        try {
          const selectedText = getSelectedText();
          if (!selectedText) {
            output.showToast('❌ 未选中文字');
            return;
          }

          const strippedText = stripChineseText(selectedText);
          await output.copyToClipboard(strippedText);
          output.showToast('✅ 已去中文并复制');
        } catch (err) {
          output.showToast('❌ 去中文失败: ' + err.message);
        }
      });

      base64Btn.insertAdjacentElement('afterend', stripChineseBtn);
    }
  }

  namespace.base64 = {
    decodeBase64Utf8,
    stripChineseText,
    injectBase64Button,
  };
})();


/* ===== src/content/messages.js ===== */
/* Linux.do 工具箱 — popup 消息通信模块 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  function assertExportResult(result) {
    if (result.total === 0) throw new Error('当前页面没有检测到已加载楼层');
    if (result.successCount === 0) throw new Error('已加载楼层全部导出失败');
  }

  function getExportToastPrefix(result) {
    if (result.failureCount === 0) return '✅';
    return `⚠️ 已处理 ${result.successCount}/${result.total} 个楼层，${result.failureCount} 个失败。`;
  }

  function registerMessageHandlers() {
    const { discourse, output, postExport, settings: settingsApi } = namespace;

    chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
      if (msg.action === 'getInfo') {
        const postEls = discourse.getPostElements();
        sendResponse({
          title: discourse.getTopicTitle(),
          url: discourse.getTopicUrl(),
          postCount: postEls.length,
        });
        return true;
      }

      if (msg.action === 'refreshEnhancements') {
        namespace.app?.refreshEnhancements?.();
        sendResponse({ success: true });
        return true;
      }

      if (msg.action === 'copyTopic') {
        (async () => {
          try {
            const settings = await settingsApi.getSettings();
            const result = await postExport.collectLoadedPosts(settings);
            assertExportResult(result);
            const md = output.formatTopicMd(result.posts, discourse.getTopicTitle(), discourse.getTopicUrl(), settings);
            await output.copyToClipboard(md);
            sendResponse({ success: true, ...result });
            const prefix = getExportToastPrefix(result);
            output.showToast(result.failureCount === 0 ? '✅ 已复制整个主题' : `${prefix} 已复制`);
          } catch (err) {
            sendResponse({ success: false, error: err.message });
            output.showToast('❌ 失败: ' + err.message);
          }
        })();
        return true;
      }

      if (msg.action === 'downloadTopic') {
        (async () => {
          try {
            const settings = await settingsApi.getSettings();
            const result = await postExport.collectLoadedPosts(settings);
            assertExportResult(result);
            const title = discourse.getTopicTitle();
            const md = output.formatTopicMd(result.posts, title, discourse.getTopicUrl(), settings);
            const filename = output.sanitizeFilename(`${title}.md`);
            output.downloadFile(md, filename);
            sendResponse({ success: true, filename, ...result });
            const prefix = getExportToastPrefix(result);
            output.showToast(result.failureCount === 0 ? `✅ 已下载 ${filename}` : `${prefix} 已下载 ${filename}`);
          } catch (err) {
            sendResponse({ success: false, error: err.message });
            output.showToast('❌ 失败: ' + err.message);
          }
        })();
        return true;
      }

      return false;
    });
  }

  namespace.messages = {
    registerMessageHandlers,
  };
})();


/* ===== src/content/index.js ===== */
/* Linux.do 工具箱 — Content Script 入口 */
(() => {
  'use strict';

  const namespace = globalThis.LinuxDoToolkit = globalThis.LinuxDoToolkit || {};

  let refreshTimer = null;
  let base64Timer = null;
  let refreshInFlight = false;
  let refreshPending = false;

  async function refreshEnhancements() {
    if (refreshInFlight) {
      refreshPending = true;
      return;
    }

    refreshInFlight = true;
    Promise.resolve().then(async () => {
      // 分栏会隐藏原生 post stream。必须先完成布局隔离，
      // 再给当前可见分页楼层注入按钮，避免改动原生滚动流导致抖动。
      await namespace.layout.applyTopicSplitLayout();
      await namespace.buttons.injectButtons();
      await namespace.base64.injectBase64Button();
    }).catch(() => {
      // 页面增强失败不应影响宿主页面，后续 DOM 变化会再次触发刷新。
    }).finally(() => {
      refreshInFlight = false;
      if (refreshPending) {
        refreshPending = false;
        scheduleRefreshEnhancements();
      }
    });
  }

  function scheduleRefreshEnhancements(delay = 150) {
    if (refreshTimer) clearTimeout(refreshTimer);
    refreshTimer = setTimeout(() => {
      refreshTimer = null;
      refreshEnhancements();
    }, delay);
  }

  function scheduleBase64ButtonRefresh(delay = 100) {
    if (base64Timer) clearTimeout(base64Timer);
    base64Timer = setTimeout(() => {
      base64Timer = null;
      namespace.base64.injectBase64Button();
    }, delay);
  }

  function bindDynamicPageEvents() {
    document.addEventListener('selectionchange', () => {
      scheduleBase64ButtonRefresh();
    });

    const observer = new MutationObserver((mutations) => {
      const onlyToolkitChanges = mutations.every((mutation) => {
        const target = mutation.target;
        const addedNodes = Array.from(mutation.addedNodes || []);
        const removedNodes = Array.from(mutation.removedNodes || []);

        return (
          target?.closest?.('.ldtk-topic-split-wrapper') ||
          addedNodes.concat(removedNodes).every((node) => (
            node.nodeType !== Node.ELEMENT_NODE ||
            node.matches?.('[class^="ldtk-"], [id^="ldcopy-"]') ||
            node.closest?.('.ldtk-topic-split-wrapper')
          ))
        );
      });

      if (!onlyToolkitChanges) scheduleRefreshEnhancements();
    });
    observer.observe(document.querySelector('#main-outlet, #main, body') || document.body, {
      childList: true,
      subtree: true,
    });

    window.addEventListener('discourse-navigate-completed', () => scheduleRefreshEnhancements(0));
    window.addEventListener('page:change', () => scheduleRefreshEnhancements(0));
  }

  function init() {
    namespace.app = { refreshEnhancements };
    namespace.messages.registerMessageHandlers();
    refreshEnhancements();
    bindDynamicPageEvents();
    namespace.settings.onSettingsChanged(refreshEnhancements);
  }

  init();
})();
