#!/usr/bin/env node
/* Linux.do 工具箱 — 零依赖构建脚本 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');

const contentFiles = [
  'src/common/settings.js',
  'src/content/markdown.js',
  'src/content/discourse.js',
  'src/content/layout.js',
  'src/content/output.js',
  'src/content/post-export.js',
  'src/content/buttons.js',
  'src/content/base64.js',
  'src/content/messages.js',
  'src/content/index.js',
];

const popupFiles = [
  'src/common/settings.js',
  'src/popup/index.js',
];

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function bundle(files, banner) {
  return banner + '\n' + files.map((file) => {
    const fullPath = path.join(root, file);
    return `\n/* ===== ${file} ===== */\n` + fs.readFileSync(fullPath, 'utf8').trim() + '\n';
  }).join('\n');
}

function writeGenerated(file, content) {
  fs.writeFileSync(path.join(root, file), content);
  fs.writeFileSync(path.join(dist, file), content);
}

ensureDir(dist);
ensureDir(path.join(dist, 'icons'));

writeGenerated('content.js', bundle(contentFiles, '/* Generated by scripts/build.js. Source: src/content/*.js */'));
writeGenerated('popup.js', bundle(popupFiles, '/* Generated by scripts/build.js. Source: src/popup/*.js */'));

for (const file of ['manifest.json', 'popup.html', 'styles.css', 'background.js', 'README.md']) {
  copyFile(path.join(root, file), path.join(dist, file));
}

for (const file of fs.readdirSync(path.join(root, 'icons'))) {
  copyFile(path.join(root, 'icons', file), path.join(dist, 'icons', file));
}

console.log('✅ Build complete: root generated files and dist/ are up to date.');
